services:
  - type: web
    name: nestarium
    runtime: docker
    plan: free
    region: ohio
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    maxShutdownDelaySeconds: 30
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: WEB_ROOT
        value: /app/build/web
