// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEhSgLxjaw-IXDYXr0eeXX8g_XRLK2VU',
    appId: '1:81511294060:web:408b697964b50bf7e82449',
    messagingSenderId: '81511294060',
    projectId: 'egg-hatchers-dev',
    authDomain: 'egg-hatchers-dev.firebaseapp.com',
    storageBucket: 'egg-hatchers-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2odwWujB00AWrUJ7CWulnTBF1RWb3gs',
    appId: '1:81511294060:android:3df1ba1f385602cae82449',
    messagingSenderId: '81511294060',
    projectId: 'egg-hatchers-dev',
    storageBucket: 'egg-hatchers-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8s37G8kwdrgJdGbcjtXkUew2j-sABsXw',
    appId: '1:81511294060:ios:29f88a51064c31c9e82449',
    messagingSenderId: '81511294060',
    projectId: 'egg-hatchers-dev',
    storageBucket: 'egg-hatchers-dev.firebasestorage.app',
    iosBundleId: 'com.egghatchers.game',
  );
}
