import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// The ledger enumerates technical compatibility references, not player copy.
const root = resolve(import.meta.dirname, '..');
const ledgerPath = 'docs/LEGACY_BRAND_REFERENCES.json';
const docs = new Set(['AGENTS.md', 'README.md', 'PROJECT_HANDOFF.md',
  'docs/NESTARIUM_MIGRATION.md', 'docs/PLATFORM_ARCHITECTURE_WORKPLAN.md',
  'cloudflare/playtest/README.md']);
const files = execFileSync('git', ['ls-files', '-z', '--cached', '--others',
  '--exclude-standard'], { cwd: root, encoding: 'utf8' }).split('\0');
const legacy = /egg[ _-]?hatchers(?:[._-][a-z0-9_-]+)?/gi;
const entries = [];
const failures = [];
for (const path of [...new Set(files)].sort()) {
  if (!path || path === ledgerPath || path === 'tool/audit_brand.mjs') continue;
  const bytes = readFileSync(resolve(root, path));
  if (bytes.includes(0)) continue;
  const lines = bytes.toString('utf8').split(/\r?\n/);
  lines.forEach((line, i) => {
    const matches = [...line.matchAll(legacy)];
    if (!matches.length) return;
    let reason;
    if (docs.has(path)) reason = 'Documented compatibility identity, origin, or migration history.';
    else if (/^import .*package:egg_hatchers\//.test(line)) reason = 'Stable Dart package/import identity.';
    else if (/com\.egghatchers\.game/.test(line)) reason = 'Installed application/bundle identity and matching native test target.';
    else if (/egg-hatchers-dev/.test(line)) reason = 'Existing Firebase project, app configuration, endpoint, or rules-test target.';
    else if (/egg-hatchers-playtest/.test(line)) reason = 'Existing protected origin/Worker; preserves browser storage and deployment history.';
    else if (/EGG_HATCHERS_/.test(line)) reason = 'Backward-compatible server environment option or its regression test.';
    else if (/eggHatchersActiveAccountId|egg_hatchers_(player_state|player_progress|cloud_progress|save)|egg_hatchers\.(settings|device_guest_slot|sync_checkpoint)/.test(line)) reason = 'Persisted save, account, settings, or wire-format contract (including tests).';
    else if (/products\/egg_hatchers|\.doc\('egg_hatchers'\)/.test(line)) reason = 'Existing owner-scoped Firestore progress document.';
    else if (path === 'pubspec.yaml' && line === 'name: egg_hatchers') reason = 'Stable private Dart package identity.';
    else if (['linux/CMakeLists.txt', 'windows/CMakeLists.txt'].includes(path)) reason = 'Existing native executable/build identity; keep installed launch compatibility.';
    else if (path === 'windows/runner/Runner.rc' && /CompanyName|ProductName|OriginalFilename/.test(line)) reason = 'Windows preference-directory identity or existing executable filename.';
    if (!reason) failures.push(`${path}:${i + 1}: unclassified legacy branding`);
    else entries.push({ path, line: i + 1, references: matches.map(m => m[0]), reason });
  });
}
if (failures.length) throw new Error(failures.join('\n'));
const windows = readFileSync(resolve(root, 'windows/runner/Runner.rc'), 'utf8');
for (const field of ['CompanyName', 'ProductName']) {
  if (!windows.includes(`VALUE "${field}", "Egg Hatchers"`)) {
    throw new Error(`Windows ${field} changed: verify preference-path migration first.`);
  }
}
const report = JSON.stringify({ product: 'Nestarium', publicDomain: 'playnestarium.com',
  note: 'Generated by node tool/audit_brand.mjs --write. Line numbers are current source locations.',
  entries }, null, 2) + '\n';
if (process.argv.includes('--write')) writeFileSync(resolve(root, ledgerPath), report);
else if (readFileSync(resolve(root, ledgerPath), 'utf8').replaceAll('\r\n', '\n') !== report) {
  throw new Error('Compatibility ledger is stale; review changes and run with --write.');
}
console.log(`Nestarium audit: ${entries.length} classified legacy references; no unclassified branding.`);
